version: '3.7'

services:
  regression:
    image: pytest:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Nintondo:/usr/workspace/Nintondo
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace/Nintondo/AutoTests/Tests