version: '3.8'

services:
  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium-tests
    volumes:
      - ./Nintondo:/usr/workspace/Nintondo  # Том для проекта
      - /tmp/.X11-unix:/tmp/.X11-unix  # Проброс X11
    working_dir: /usr/workspace/Nintondo/AutoTests/tests  # Рабочая директория для тестов
    command: "/usr/local/bin/pytest -s mane_site_tests/test_connect.py"
    environment:
      - DISPLAY=${DISPLAY}  # Использование переменной окружения DISPLAY для подключения X11
      - PYTHONPATH=/usr/workspace/Nintondo  # Указание PYTHONPATH
    ports:
      - "4444:4444"  # Selenium WebDriver порт
    networks:
      - selenium_network

networks:
  selenium_network:
    driver: bridge