version: '3.8'

services:
  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium-tests
    volumes:
      - ./Nintondo:/usr/workspace/Nintondo  # Оставляем текущий volume для кода
      - /tmp/.X11-unix:/tmp/.X11-unix  # Для X11
      - ./allure-results:/app/allure-results  # Добавляем volume для хранения отчетов Allure
    working_dir: /usr/workspace/Nintondo/AutoTests/tests  # Рабочая директория для тестов
    command:
      - pytest
      - --alluredir=/app/allure-results  # Указываем директорию для отчетов
    environment:
      - DISPLAY=${DISPLAY}  # Используем переменную DISPLAY для X11
      - PYTHONPATH=/usr/workspace/Nintondo  # Указываем PYTHONPATH
    ports:
      - "4444:4444"  # Selenium WebDriver порт
    networks:
      - selenium_network

networks:
  selenium_network:
    driver: bridge