version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium-tests
    user: root  # Запуск контейнера от имени root
    volumes:
      - ./Nintondo:/usr/workspace/Nintondo
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    working_dir: /usr/workspace/Nintondo/AutoTests/tests
    command: /bin/sh -c "mkdir -p /app/allure-results /app/allure-report && pytest -s /usr/workspace/Nintondo/AutoTests/tests/ --alluredir=/app/allure-results && sleep 10 && allure generate /app/allure-results --clean -o /app/allure-report"
    environment:
      - DISPLAY=${DISPLAY}
    ports:
      - "4444:4444"
    networks:
      - selenium_network

  allure:
    image: frankescobar/allure-docker-service:latest
    container_name: allure-report
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    ports:
      - "4040:4040"
    entrypoint: /bin/sh -c "allure generate /app/allure-results --clean -o /app/allure-report && while true; do sleep 60; done"  # Ожидание работы Allure, чтобы не завершался раньше времени

networks:
  selenium_network:
    driver: bridge
