version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium-tests
    volumes:
      - ./Nintondo:/usr/workspace/Nintondo
    working_dir: /usr/workspace/Nintondo/AutoTests/Tests
    command: xvfb-run -a pytest -s  # Запуск через Xvfb для headless-режима
    environment:
      - DISPLAY=:99  # Используется виртуальный дисплей
    ports:
      - "4444:4444"
    networks:
      - selenium_network

networks:
  selenium_network:
    driver: bridge