version: '3.8'

services:
  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium-tests
    volumes:
      - ./Nintondo:/usr/workspace/Nintondo  
      - /tmp/.X11-unix:/tmp/.X11-unix  
    working_dir: /usr/workspace/Nintondo/AutoTests/tests  # Working directory for tests
    command:
      - pytest 
      - -s
    environment:
      - DISPLAY=${DISPLAY}  # Using the DISPLAY environment variable to connect X11
      - PYTHONPATH=/usr/workspace/Nintondo  # Specifying PYTHONPATH
    ports:
      - "4444:4444"  # Selenium WebDriver порт
    networks:
      - selenium_network

networks:
  selenium_network:
    driver: bridge