version: '3.7'

services:
  regression:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
      - allure-results:/usr/workspace/allure-results
    command: /bin/sh -c "pytest -sv --alluredir=/usr/workspace/allure-results"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
      - DISPLAY=${DISPLAY} 

  # Добавляем сервис для генерации отчета Allure
  allure:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - allure-results:/usr/workspace/allure-results
      - ./allure-report:/usr/workspace/allure-report
    command: /bin/sh -c "allure generate /usr/workspace/allure-results --clean -o /usr/workspace/allure-report"
    working_dir: /usr/workspace

volumes:
  allure-results:
